import Head from "next/head";
import { useCallback, useState, useRef, memo, useMemo, useEffect } from "react";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>About</h1>
      </div>
    </>
  );
}
