import Head from "next/head";
import { useCallback, useState, useRef, memo, useMemo, useEffect } from "react";
import { Container, ThemeProvider } from "@mui/system";
import theme from "@/themes";
import { Button, Stack, Box, Grid, Paper } from "@mui/material";
import { SignupForm } from "@/components/SignupForm";
import { LoginForm } from "@/components/LoginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Container maxWidth="xs">
          {/*
          <Stack
            spacing={2}
            sx={{
              mt: 2,
              px: 2,
              height: "100%",
              bgcolor: "primary.main",
            }}
            alignItems="flex-end"
            justifyContent="center"
          >
            <Box>
              <Button variant="contained"> Hello world!</Button>
            </Box>
            <Box>
              <Button variant="outlined" color="secondary">
                Hello world!!!
              </Button>
            </Box>
            <Box>
              <Button variant="contained" color="secondary">
                Hello world!!!!!!!
              </Button>
            </Box>
            <Button variant="outlined" color="secondary">
              Hello world!
            </Button>
            <Stack direction={"row"} width="100%" spacing={2}>
              <Button variant="contained" sx={{ flex: 4 }}>
                {" "}
                Hello world!
              </Button>
              <Button variant="outlined" color="secondary" sx={{ flex: 2 }}>
                Hello world!
              </Button>
            </Stack>
          </Stack>
          <Box sx={{ bgcolor: "primary.main" }}>ciao</Box>*/}
          <SignupForm />
        </Container>{" "}
      </ThemeProvider>
    </>
  );
}
